name: main

on:
  schedule:
    - cron: "40 22 * * *" # 北京时间上午06:40
  # pull_request:
  #   branches: [ master ]
  workflow_dispatch:
jobs:
  CheckIn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run main
        env:
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          yarn
          yarn mailboxsend
